<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nahda Wirdiyan Fauziyyah">
<meta name="dcterms.date" content="2024-01-17">

<title>Pengaruh Tingkat Suku Bunga Terhadap Nilai Tukar Rupiah Tahun 2002 Hingga 2022</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Tingkat Suku Bunga Terhadap Nilai Tukar Rupiah Tahun 2002 Hingga 2022</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Nahda Wirdiyan Fauziyyah </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 17, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="poltekapp.jpg" class="img-fluid"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Nilai tukar rupiah terhadap mata uang asing, khususnya dolar Amerika Serikat (AS), merupakan salah satu variabel makroekonomi yang penting bagi perekonomian Indonesia. Nilai tukar rupiah dapat mempengaruhi daya saing ekspor, impor, inflasi, neraca pembayaran, dan pertumbuhan ekonomi. Nilai tukar rupiah juga dapat dipengaruhi oleh berbagai faktor, baik internal maupun eksternal. Salah satu faktor internal yang berpengaruh adalah tingkat suku bunga.</p>
<p>Tingkat suku bunga adalah harga dari penggunaan uang dalam periode tertentu. Tingkat suku bunga dapat mempengaruhi permintaan dan penawaran uang, serta arus modal antarnegara. Tingkat suku bunga yang ditetapkan oleh Bank Indonesia (BI) sebagai bank sentral Indonesia, dan tingkat suku bunga yang ditetapkan oleh Federal Reserve (The Fed) sebagai bank sentral AS, dapat mempengaruhi nilai tukar rupiah terhadap dolar AS. Secara teoritis, tingkat suku bunga yang lebih tinggi dapat menarik arus modal masuk, sehingga meningkatkan permintaan terhadap mata uang domestik dan menguatkan nilai tukarnya. Sebaliknya, tingkat suku bunga yang lebih rendah dapat mendorong arus modal keluar, sehingga menurunkan permintaan terhadap mata uang domestik dan melemahkan nilai tukarnya.</p>
<p>Penelitian tentang pengaruh tingkat suku bunga terhadap nilai tukar rupiah telah banyak dilakukan oleh para peneliti, baik dengan menggunakan pendekatan teoritis maupun empiris. Namun, hasil penelitian tersebut masih bervariasi dan belum menunjukkan kesimpulan yang konsisten. Hal ini dapat disebabkan oleh perbedaan periode, metode, variabel, dan data yang digunakan dalam penelitian. Oleh karena itu, penelitian ini bertujuan untuk menguji kembali pengaruh tingkat suku bunga terhadap nilai tukar rupiah dengan menggunakan data tahun 2002 hingga 2022. Data tahun 2002 dipilih karena merupakan tahun awal penerapan sistem nilai tukar mengambang bebas di Indonesia. Penelitian ini diharapkan dapat memberikan kontribusi bagi pengembangan ilmu pengetahuan, khususnya di bidang ekonomi internasional, serta memberikan masukan bagi pembuat kebijakan dalam mengelola nilai tukar rupiah.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Penelitian ini memanfaatkan data sekunder yang didapatkan dari Bank Indonesia, yang mencakup data historis mengenai niali tukar rupiah terhadap dolar Amerika Serikat, dan bunga BI. Penelitian ini mengeksplorasi keterkaitan antara tingkat bunga, yang mempengaruhi kurs rupiah. Penelitian ini menggunakan metode analisis regresi univariat dengan data yang bersifat time series, mencakup periode waktu dari tahun 2002 hingga 2022.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<ol type="1">
<li>Apakah Tingkat suku bunga mempengaruhi nilai tukar rupiah?</li>
<li>Bagaimana hubungan tingkat suku bunga terhadap nilai tukar rupiah?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Tujuan dari penelitian ini adalah untuk meneliti dampak tingkat bunga terhadap kurs rupiah terhadap dolar Amerika dari tahun 2002 sampai 2022. Selain itu penelitian ini memberikan informasi yang dapat digunakan oleh pelaku pasar valas untuk menentukan strategi investasi yang tepat, serta memberikan pemahaman kepada masyarakat umum tentang hubungan antara tingkat suku bunga dan nilai tukar rupiah.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Package yang digunakan dalam penelitian ini antara lain:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(writexl)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p><strong>nilai tukar rupiah</strong></p>
<p>Nilai tukar rupiah (terhadap USD) adalah jumlah rupiah yang dibutuhkan untuk membeli satu dolar AS. Nilai tukar ini berfluktuasi setiap hari, tergantung pada permintaan dan penawaran mata uang di pasar valuta asing. Nilai tukar ini juga dipengaruhi oleh faktor-faktor ekonomi, politik, dan sosial di dalam dan luar negeri.</p>
<p>Salah satu sumber informasi tentang nilai tukar rupiah (terhadap USD) adalah Bank Indonesia, bank sentral Republik Indonesia. Bank Indonesia menetapkan kurs transaksi untuk beberapa mata uang asing, termasuk dolar AS, berdasarkan harga pasar. Kurs transaksi ini digunakan sebagai acuan untuk transaksi valuta asing antara Bank Indonesia dan bank-bank lain di Indonesia.</p>
<p>Selain Bank Indonesia, ada juga sumber informasi lain yang menyediakan nilai tukar rupiah (terhadap USD), seperti Google Finance, Wise, dan media online. Namun, nilai tukar yang ditampilkan oleh sumber-sumber ini mungkin berbeda dari kurs transaksi Bank Indonesia, karena mereka menggunakan data dari berbagai penyedia layanan valuta asing yang mungkin memiliki harga yang berbeda. Oleh karena itu, Anda harus memeriksa nilai tukar dari beberapa sumber sebelum melakukan transaksi valuta asing, agar Anda mendapatkan harga yang terbaik.</p>
<p><strong>Tingkat Suku Bunga</strong></p>
<p>Tingkat suku bunga bank indonesia adalah suku bunga acuan yang ditetapkan oleh Bank Indonesia (BI) sebagai bank sentral Republik Indonesia. Suku bunga ini digunakan sebagai alat untuk mengatur kebijakan moneter, inflasi, dan nilai tukar rupiah. Suku bunga ini juga mempengaruhi suku bunga pasar uang, perbankan, dan sektor riil.</p>
<p>Saat ini, suku bunga acuan yang digunakan oleh BI adalah BI-Rate, yang sebelumnya bernama BI-7 Day Reverse Repo Rate (BI7DRR). BI-Rate adalah suku bunga yang diberlakukan oleh BI untuk transaksi reverse repo dengan tenor 7 hari. Reverse repo adalah transaksi jual beli surat berharga antara BI dan bank lain, di mana BI menjual surat berharga dengan kesepakatan untuk membelinya kembali pada waktu yang ditentukan dengan harga yang lebih tinggi. Dengan demikian, BI dapat mengendalikan jumlah uang beredar di pasar.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<table class="table">
<colgroup>
<col style="width: 2%">
<col style="width: 10%">
<col style="width: 23%">
<col style="width: 33%">
<col style="width: 17%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Tahun</th>
<th>Suku Bunga (%)</th>
<th>Nilai Tukar (IDR/USD)</th>
<th>y</th>
<th>x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>2002</td>
<td>18,25</td>
<td>9.311,00</td>
<td>3,968996327</td>
<td>0,1825</td>
</tr>
<tr class="even">
<td>2</td>
<td>2003</td>
<td>12,5</td>
<td>8.577,00</td>
<td>3,93333541</td>
<td>0,125</td>
</tr>
<tr class="odd">
<td>3</td>
<td>2004</td>
<td>8,5</td>
<td>9.290,00</td>
<td>3,968015714</td>
<td>0,085</td>
</tr>
<tr class="even">
<td>4</td>
<td>2005</td>
<td>12,75</td>
<td>9.705,00</td>
<td>3,98699554</td>
<td>0,1275</td>
</tr>
<tr class="odd">
<td>5</td>
<td>2006</td>
<td>9,75</td>
<td>9.020,00</td>
<td>3,955206538</td>
<td>0,0975</td>
</tr>
<tr class="even">
<td>6</td>
<td>2007</td>
<td>8</td>
<td>9.419,00</td>
<td>3,974004797</td>
<td>0,08</td>
</tr>
<tr class="odd">
<td>7</td>
<td>2008</td>
<td>9,5</td>
<td>10.950,00</td>
<td>4,039414119</td>
<td>0,095</td>
</tr>
<tr class="even">
<td>8</td>
<td>2009</td>
<td>6,5</td>
<td>9.399,00</td>
<td>3,97308165</td>
<td>0,065</td>
</tr>
<tr class="odd">
<td>9</td>
<td>2010</td>
<td>6,5</td>
<td>8.991,00</td>
<td>3,953807998</td>
<td>0,065</td>
</tr>
<tr class="even">
<td>10</td>
<td>2011</td>
<td>6</td>
<td>9.068,00</td>
<td>3,957511511</td>
<td>0,06</td>
</tr>
<tr class="odd">
<td>11</td>
<td>2012</td>
<td>5,75</td>
<td>9.638,00</td>
<td>3,983986922</td>
<td>0,0575</td>
</tr>
<tr class="even">
<td>12</td>
<td>2013</td>
<td>7,5</td>
<td>12.189,00</td>
<td>4,085968077</td>
<td>0,075</td>
</tr>
<tr class="odd">
<td>13</td>
<td>2014</td>
<td>7,75</td>
<td>12.440,00</td>
<td>4,09482038</td>
<td>0,0775</td>
</tr>
<tr class="even">
<td>14</td>
<td>2015</td>
<td>7,50</td>
<td>13.795,00</td>
<td>4,139721705</td>
<td>0,075</td>
</tr>
<tr class="odd">
<td>15</td>
<td>2016</td>
<td>4,75</td>
<td>13.436,00</td>
<td>4,128269995</td>
<td>0,0475</td>
</tr>
<tr class="even">
<td>16</td>
<td>2017</td>
<td>4,25</td>
<td>13.548,00</td>
<td>4,131875188</td>
<td>0,0425</td>
</tr>
<tr class="odd">
<td>17</td>
<td>2018</td>
<td>6</td>
<td>14.481,00</td>
<td>4,160798554</td>
<td>0,06</td>
</tr>
<tr class="even">
<td>18</td>
<td>2019</td>
<td>5</td>
<td>13.901,00</td>
<td>4,143046043</td>
<td>0,05</td>
</tr>
<tr class="odd">
<td>19</td>
<td>2020</td>
<td>3,75</td>
<td>14.146,00</td>
<td>4,150633654</td>
<td>0,0375</td>
</tr>
<tr class="even">
<td>20</td>
<td>2021</td>
<td>3,5</td>
<td>14.305,00</td>
<td>4,155487862</td>
<td>0,035</td>
</tr>
<tr class="odd">
<td>21</td>
<td>2022</td>
<td>6</td>
<td>15.636,80</td>
<td>4,194147881</td>
<td>0,06</td>
</tr>
</tbody>
</table>
<p>pada penelitian ini data bersifat time series dalam kurun waktu tahun 2002 hingga 2022. Penelitian ini menggunakan data objek nilai tukar rupiah dan suku bunga yang didapat dari Statistik Ekonomi dan Keuangan Indonesia (SEKI). Kemudian data diola sedemikian rupa dan menghasilkan variabel x dan variabel y, yang nantinya akan digunakan sebagai objek pada penelitian ini.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#import dataset</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>suku<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'suku.xlsx'</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(suku)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  Tahun `Suku Bunga (%)` `Nilai Tukar (IDR/USD)`     y      x
  &lt;dbl&gt;            &lt;dbl&gt;                   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
1  2002            18.2                     9311  3.97 0.182 
2  2003            12.5                     8577  3.93 0.125 
3  2004             8.5                     9290  3.97 0.085 
4  2005            12.8                     9705  3.99 0.128 
5  2006             9.75                    9020  3.96 0.0975
6  2007             8                       9419  3.97 0.08  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(suku,<span class="fu">aes</span>(y</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>,x</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>))<span class="sc">+</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"purple"</span>,<span class="at">size=</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"hubungan antara nilai tukar rupiah dan suku bunga "</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"suku bunga"</span>,</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"nilai tukar rupiah"</span>,</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"sumber: SEKI"</span>)<span class="sc">+</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Peneliti menggunakan metode regresi univariat, dengan teknik analisis berupa kuantitatif deskriptif. Penelitian ini bermaksud untuk mencari hubungan antara tingkat suku bunga dari bank Indonesia dengan nilai tukar rupiah. Dengan spesifikasi sebagai berikut:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah nilai tukar rupiah (kurs rupiah) dan <span class="math inline">\(x_t\)</span> adalah suku bunga.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<p>peneliti menyatukan data yang telah dikumpulkan, selanjutnya melakukan regresi dan menghasilkan data sebagai berikut:</p>
<table class="table">
<thead>
<tr class="header">
<th>Coefficients</th>
<th>Estimate</th>
<th>Pr(&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>4.16359</td>
<td>&lt; 2e-16</td>
</tr>
<tr class="even">
<td>x</td>
<td>-1.47265</td>
<td>0.00651</td>
</tr>
</tbody>
</table>
<p>Hasil dari regresi ditersebut dimasukkan kedalam rumus sehingga menjadi:</p>
<p><span class="math display">\[
y_{t}=\ 4.16359   - \  1.47265 x_t+\mu_t
\]</span></p>
<p>Suku bunga berpengaruh negatif terhadap kurs rupiah, maka jika diasumsikan suku bunga naik satu akan menyebabkan penurunan atau melemahnya kurs rupiah sebesar 1.47265.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/metodologi/uasnahda"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>suku<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"suku.xlsx"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>reg<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>suku)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x, data = suku)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.11772 -0.07040  0.03087  0.04536  0.11892 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.16359    0.04024 103.471  &lt; 2e-16 ***
x           -1.47265    0.48202  -3.055  0.00651 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.07536 on 19 degrees of freedom
Multiple R-squared:  0.3294,    Adjusted R-squared:  0.2941 
F-statistic: 9.334 on 1 and 19 DF,  p-value: 0.006514</code></pre>
</div>
</div>
<p>plot pengaruh error terhadap suku bunga</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>suku<span class="sc">$</span>m<span class="ot">&lt;-</span><span class="fu">resid</span>(reg)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(suku<span class="sc">$</span>x,suku<span class="sc">$</span>m,<span class="at">xlab=</span><span class="st">"suku bunga"</span>,<span class="at">ylab=</span><span class="st">"error"</span>,<span class="at">col=</span><span class="st">'maroon'</span>,<span class="at">pch=</span><span class="dv">16</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>plot pengaruh error terhadap kurs rupiah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>suku<span class="sc">$</span>m<span class="ot">&lt;-</span><span class="fu">resid</span>(reg)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(suku<span class="sc">$</span>y,suku<span class="sc">$</span>m,<span class="at">xlab=</span><span class="st">"kurs rupiah"</span>,<span class="at">ylab=</span><span class="st">"error"</span>,<span class="at">col=</span><span class="st">'pink'</span>,<span class="at">pch=</span><span class="dv">16</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Jika ilihat dari hasil regresi,p-value (0.006514) menunjukkan signifikansi model, nilai ini jauh lebih kecil dari alpha yang berarti model secara keseluruhan signifikan dalam menjelaskan hubungan antara x dan y.</p>
<p>Nilai Multiple R-squared 0.3294, Adjusted R-squared 0.2941, menunjukkan bahwa model dapat menjelaskan sekitar 33% dan 29% variasi dari variabel y. Nilai ini cukup rendah, yang berarti model mungkin tidak memiliki daya prediksi yang baik. Maka peneliti perlu menambahkan variabel lain yang relevan dengan y.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Suku bunga memiliki pengaruh yang signifikan terhadap kurs rupiah dalam kurun waktu periode tahun 2000 hingga 2022. Namun suku bunga memiliki efek negatif teradap kurs rupia, yang artinya setiap kenaikan dari suku bunga akan melemahkan atau menurunkan kurs rupiah. Namun signifikansi tidak menjamin bahwa regresi memiliki daya prediksi yang baik, pada penelitian ini menunjukkan daya prediksi yang kurang. Peneliti perlu melakukan analisis variabel lain yang tidak teramati seperti inflasi, pertumbuhan ekonomi, dan kebijakan pemerintah.</p>
<p>Ada beberapa situasi di mana kenaikan suku bunga dapat membuat nilai tukar rupiah melemah. Situasi tersebut dapat terjadi apabila Kondisi ekonomi dunia sedang menghadapi krisis atau perlambatan pertumbuhan. Dalam situasi ini, investor dunia cenderung untuk menarik investasi mereka dari seluruh dunia, termasuk dari Indonesia. Selain itu apabila Neraca perdagangan Indonesia mengalami deficit, dalam situasi ini, kebutuhan valuta asing untuk impor akan naik, sehingga membuat nilai tukar rupiah melemah.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Faoriko, A. (2013). Pengaruh inflasi, suku bunga dan nilai tukar rupiah, terhadap return saham di bursa efek Indonesia. Universitas Negeri Yogyakarta.</p>
<p>Astuti, E. P., &amp; Ardila, R. (2019). Pengaruh Perubahan Tingkat Suku Bunga Bank Indonesia dan Perubahan Nilai Tukar Rupiah pada US Dollar terhadap Harga Saham-Saham LQ45 di Bursa Efek Indonesia. Jurnal Sekuritas, 2(3), 65-82.</p>
<p>Hidayat, A., &amp; Saefullah, E. (2019). Nilai tukar rupiah dan suku bunga bank indonesia terhadap indeks harga saham gabungan Bursa Efek Indonesia periode 2012-2017. Banque Syar’i: Jurnal llmiah Perbankan Syariah, 5(2), 165-182.</p>
<p>Arifin, S., &amp; Mayasya, S. (2018). Faktor-faktor yang mempengaruhi nilai tukar rupiah terhadap dolar amerika serikat. Jurnal Ekonomi-Qu, 8(1).</p>
<p>Ardiyanto, F., &amp; Ma’ruf, A. (2014). Pergerakan Nilai Tukar Rupiah Terhadap Dolar Amerika Dalam Dua Periode Penerapan Sistem Nilai Tukar. Jurnal Ekonomi &amp; Studi Pembangunan, 15(2), 127-134.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>